#!/bin/env python3
import os
from tomlkit.items import KeyType
from typing import Never
from modules.filemanager import file_manager

def template():
    NameReal = input("Username: ")
    KeyType = 'DSA'
    SubkeyLength = 1024
    SubkeyType = "ELG-E"
    DSAKeyLength = 1024
    NameEmail: str = input("Email Address: ")
    Passphrase = input("Password: ")
    NameComment = "Cybercraft Standard Basic Config Generated User Key"
    ExpireDate = 0

    with file_manager('/tmp/foo', 'w') as f:
        f.write(f'%echo Generating a basic OpenPGP key\n')

    with file_manager('/tmp/foo', 'a') as f:
        f.write(f'Key-Type: {KeyType}\n')
        f.write(f'Subkey-Type: {SubkeyType}\n')
        f.write(f'Subkey-Length: {SubkeyLength}\n')
        f.write(f'Name-Real: {NameReal}\n')
        f.write(f'Name-Comment: {NameComment}\n')
        f.write(f'Name-Email: {NameEmail}\n')
        f.write(f'Expire-Date: {ExpireDate}\n')
        f.write(f'Passphrase: {Passphrase}\n')
        f.write(f'%commit\n')
        f.write(f'%echo done\n')

    os.system("gpg --batch --generate-key /tmp/foo")
    os.remove('/tmp/foo')
    os.system("gpg --list-secret-keys")
    print('Please Write Down your Passphrase\notherwise you will lose access')


def expert_guide():
    print('PLACEHOLDER')

def interactive_guide():
    print('''BASIC CONFIGURATION:
 --------------------
 KeyType      - DSA
 SubkeyLength - 1024
 SubkeyType   - ELG-E
 DSAKeyLength - 1024
 Expires      - Never
 --------------------
        ''')
    basic = input('Do you wanna use the basic config? <y/n>: ')
    if basic.upper() == 'Y':
        template()
    elif basic.upper() == 'N':
        expert_guide()
    else:
        print('Invalid user input.')
        interactive_guide()


interactive_guide()
