name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: installing libs
      run: apt-get libyaml-cpp-dev -y
    - name: building cc binary
      run: make build
