name: C/C++ CI

on:
  push:
    branches: [ "main", "latest", "nightly" ]
  pull_request:
    branches: [ "main", "latest", "nightly" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: installing libs
      run: sudo apt-get install libyaml-cpp-dev -y
    - name: building cc binary
      run: make buildclean
